name: Worker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  GetGo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'
      - run: go version