name: Worker
on:
  push:
    branches:
      - main
      - Build-Go
  pull_request:
    branches:
      - main
jobs:
  GetGo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - run: go version
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: GoLang
          path: .
  BuildFrontEnd:
    runs-on: ubuntu-latest
    needs: GetGo
    steps:
      - uses: actions/checkout@v2
      - name: Build go.mod
        working-directory: frontend
        run: go build
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: .
  RunFrontEnd:
    runs-on: ubuntu-latest
    needs: BuildFrontEnd
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/checkout@v2
      - name: Run Go
        working-directory: frontend
        run: go test .


