name: Worker
on:
  push:
    branches:
      - main
      - Build-Go
  pull_request:
    branches:
      - main
jobs:
  GetGo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - run: go version
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: GoLang
          path: .
  BuildFrontEnd:
    runs-on: ubuntu-latest
    needs: GetGo
    steps:
      - name: set up directory
        run: actions/checkout@v2
      - name: get Path
        run: pwd
      #- name: Check if File Exits
      #  run: go build ./frontend/
      - name: go run
        run: go run ./frontend/main.go

